# Generated by Django 2.0 on 2019-03-09 08:22

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Img',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_file', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='MassageProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=300)),
                ('image', models.ImageField(upload_to='')),
                ('number_ordering', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(6), django.core.validators.MinValueValidator(1)])),
            ],
            options={
                'ordering': ['number_ordering'],
            },
        ),
        migrations.CreateModel(
            name='Masseur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('basic_photo', models.ImageField(upload_to='')),
                ('rear_profile_photo', models.ImageField(blank=True, upload_to='')),
                ('work_time', models.CharField(max_length=3)),
                ('description', models.TextField()),
                ('ordinal_number', models.IntegerField()),
            ],
            options={
                'ordering': ['ordinal_number'],
            },
        ),
        migrations.CreateModel(
            name='PostDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('img', models.ImageField(upload_to='')),
                ('description', models.TextField()),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['added_at'],
            },
        ),
        migrations.AddField(
            model_name='img',
            name='masseur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Masseur'),
        ),
    ]
