# Generated by Django 2.0 on 2019-03-09 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='masseur',
            old_name='rear_profile_photo',
            new_name='back_profile_photo',
        ),
    ]
