# Generated by Django 2.0 on 2019-03-09 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190309_0922'),
    ]

    operations = [
        migrations.CreateModel(
            name='PolishCV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex', models.CharField(choices=[('M', 'Pan'), ('W', 'Pani')], max_length=2)),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('street', models.CharField(max_length=50)),
                ('zip_code', models.CharField(max_length=10)),
                ('phone_number', models.CharField(max_length=15)),
                ('e_mail', models.EmailField(max_length=254)),
                ('cv', models.FileField(upload_to='app/documents/')),
                ('photo_1', models.ImageField(upload_to='')),
                ('photo_2', models.ImageField(upload_to='')),
                ('photo_3', models.ImageField(upload_to='')),
                ('privacy_policy', models.BooleanField(default=False)),
                ('work_experience_in_year', models.CharField(choices=[('1', 'poniżej 1 roku'), ('1_2', 'od 1 roku do 2 lat'), ('2_4', 'od 2 do 4 lat'), ('4', 'powyżej 4 lat')], default=None, max_length=5)),
                ('classic_massage', models.CharField(choices=[('1', 'nie znam'), ('2', 'znam podstawy'), ('3', 'poziom średnim'), ('4', 'poziom średnio-zaawansowanym'), ('5', 'poziom zaawansowanym')], default=None, max_length=1)),
                ('relaks_massage', models.CharField(choices=[('1', 'nie znam'), ('2', 'znam podstawy'), ('3', 'poziom średnim'), ('4', 'poziom średnio-zaawansowanym'), ('5', 'poziom zaawansowanym')], default=None, max_length=1)),
                ('sport_massage', models.CharField(choices=[('1', 'nie znam'), ('2', 'znam podstawy'), ('3', 'poziom średnim'), ('4', 'poziom średnio-zaawansowanym'), ('5', 'poziom zaawansowanym')], default=None, max_length=1)),
                ('taj_massage', models.CharField(choices=[('1', 'nie znam'), ('2', 'znam podstawy'), ('3', 'poziom średnim'), ('4', 'poziom średnio-zaawansowanym'), ('5', 'poziom zaawansowanym')], default=None, max_length=1)),
                ('checolate_massage', models.CharField(choices=[('1', 'nie znam'), ('2', 'znam podstawy'), ('3', 'poziom średnim'), ('4', 'poziom średnio-zaawansowanym'), ('5', 'poziom zaawansowanym')], default=None, max_length=1)),
                ('limfatic_massage', models.CharField(choices=[('1', 'nie znam'), ('2', 'znam podstawy'), ('3', 'poziom średnim'), ('4', 'poziom średnio-zaawansowanym'), ('5', 'poziom zaawansowanym')], default=None, max_length=1)),
                ('massage_skills', models.TextField()),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-added_at'],
            },
        ),
    ]
